[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "   "
version = "0.1.0"
description = "    "
authors = [{ name = "Jonny Jamison", email = "jonnyjamison@outlook.com" }]
dependencies = []